linters:
    disable-all: true
    enable:
        - deadcode
        - errcheck
        - govet
        - ineffassign
        - typecheck
        - varcheck
        - dupl
        - funlen
        - goconst
        - gocyclo
        - gocritic
        - goimports
        - goprintffuncname
        - gosec
        - lll
        - nakedret
        - unconvert
linters-settings:
    funlen:
        lines: 150
        statements: 80
