before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./cmd/aqua
    binary: aqua

    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - name_template: "{{ .Os }}_{{ .Arch }}_v{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
  github:
    owner: aquasecurity
    name: trivy-plugin-aqua
