name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "SAAS-12397-dockerize-trivy-plugin"
usage: trivy aqua <srcPath>
description: A Trivy plugin that sends results to Aqua.
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/SAAS-12397-dockerize-trivy-plugin/linux_amd64_SAAS-12397-dockerize-trivy-plugin.tar.gz
    bin: ./aqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/SAAS-12397-dockerize-trivy-plugin/linux_arm64_SAAS-12397-dockerize-trivy-plugin.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/SAAS-12397-dockerize-trivy-plugin/darwin_amd64_SAAS-12397-dockerize-trivy-plugin.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/SAAS-12397-dockerize-trivy-plugin/darwin_arm64_SAAS-12397-dockerize-trivy-plugin.tar.gz
    bin: ./aqua
