name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "v0.89.2-test-commercial-rules"
usage: trivy aqua <srcPath>
description: A Trivy plugin that sends results to Aqua.
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.89.2-test-commercial-rules/linux_amd64_v0.89.2-test-commercial-rules.tar.gz
    bin: ./aqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.89.2-test-commercial-rules/linux_arm64_v0.89.2-test-commercial-rules.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.89.2-test-commercial-rules/darwin_amd64_v0.89.2-test-commercial-rules.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.89.2-test-commercial-rules/darwin_arm64_v0.89.2-test-commercial-rules.tar.gz
    bin: ./aqua
