name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "0.1.1"
usage: send iac scan results to aqua. 
description: |-
  A Trivy plugin that uses Aqua for IaC scanning.
  Usage: trivy aqua TYPE[.VERSION][.GROUP] NAME
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.1.1-prerelease/0.1.1.tar.gz
    bin: ./bin/scannerclistatic
