name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "v0.205.4"
maintainer: aquasecurity
summary: Send results to Aqua Security
description: A plugin for integration with Aqua Security SaaS platform
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.205.4/linux_amd64_v0.205.4.tar.gz
    bin: ./aqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.205.4/linux_arm64_v0.205.4.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.205.4/darwin_amd64_v0.205.4.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.205.4/darwin_arm64_v0.205.4.tar.gz
    bin: ./aqua
  - selector:
      os: windows
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.205.4/windows_amd64_v0.205.4.tar.gz
    bin: ./aqua
