name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "tag-for-fips"
usage: trivy aqua <srcPath>
description: A Trivy plugin that sends results to Aqua.
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/tag-for-fips/linux_amd64_tag-for-fips.tar.gz
    bin: ./aqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/tag-for-fips/linux_arm64_tag-for-fips.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/tag-for-fips/darwin_amd64_tag-for-fips.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/tag-for-fips/darwin_arm64_tag-for-fips.tar.gz
    bin: ./aqua
  - selector:
      os: windows
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/tag-for-fips/windows_amd64_tag-for-fips.tar.gz
    bin: ./aqua
