name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "optimize-storage"
usage: trivy aqua <srcPath>
description: A Trivy plugin that sends results to Aqua.
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/optimize-storage/linux_amd64_optimize-storage.tar.gz
    bin: ./aqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/optimize-storage/linux_arm64_optimize-storage.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/optimize-storage/darwin_amd64_optimize-storage.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/optimize-storage/darwin_arm64_optimize-storage.tar.gz
    bin: ./aqua
  - selector:
      os: windows
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/optimize-storage/windows_amd64_optimize-storage.tar.gz
    bin: ./aqua
