name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-aqua
version: "v0.7.0"
usage: send trivy results to CSPM.
description: |-
  A Trivy plugin that sends results to Aqua.
  Usage: trivy aqua <srcPath>
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.7.0/linux_amd64_v0.7.0.tar.gz
    bin: ./aqua
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.7.0/linux_arm64_v0.7.0.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.7.0/darwin_amd64_v0.7.0.tar.gz
    bin: ./aqua
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.7.0/darwin_arm64_v0.7.0.tar.gz
    bin: ./aqua
  - selector:
      os: windows
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-aqua/releases/download/v0.7.0/windows_amd64_v0.7.0.zip
    bin: aqua.exe