name: "aqua"
repository: github.com/aquasecurity/trivy-plugin-wave
version: "0.1.0"
usage: send iac scan results to aqua wave
description: |-
  A Trivy plugin that uses Aqua Wave for IaC scanning.
  Usage: trivy wave TYPE[.VERSION][.GROUP] NAME
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/trivy-plugin-wave/archive/0.1.0.zip 
    bin: ./trivy-plugin-wave 
