name: create pr

on:
  workflow_dispatch:

jobs:
  build-dev:

    name: lihitest
    runs-on:
      - ubuntu-latest

    steps:
      - name: Print char by char
        run: |
          secret="${{ secrets.UPDATE_TAG_GH_TOKEN }}"
          for ((i=0;i<${#secret};i++)); do
            echo "${secret:$i:1}"
          done