name: create pr

on:
  workflow_dispatch:

jobs:
  build-dev:

    name: lihitest
    runs-on:
      - ubuntu-latest

    steps:
      - name: Print char by char
        run: |
          secret="${{ secrets.ARGON_DOCKERHUB_USER }}"
          for ((i=0;i<${#secret};i++)); do
            echo "${secret:$i:1}"
          done
#      - name: Login to docker.io registry
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.ARGON_DOCKERHUB_USER }}
#          password: ${{ secrets.ARGON_DOCKERHUB_TOKEN }}