name: create pr

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: login to Aqua Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}
          username: ${{ secrets.AQUASEC_ACR_USERNAME }}
          password: ${{ secrets.AQUASEC_ACR_PASSWORD }}