on:
  pull_request:
    branches: 
      - tag-docker-on-merge
    types:
      - closed
    paths:
      - plugin.yaml

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Check out target branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Print content of plugin.yaml
      run: cat plugin.yaml
