on:
  pull_request:
    branches: 
      - tag-docker-on-merge
    types:
      - closed
    paths:
      - plugin.yaml

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Check out target branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Login to docker.io registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract version
      run: "grep 'version: ' plugin.yaml | cut -d '\"' -f2"
      id: version
    - name: Change version to latest
      run: docker tag aquasec/aqua-scanner:${{ steps.version.outputs.stdout }} aquasec/aqua-scanner:latest
