on:
  pull_request:
    branches: 
      - tag-docker-on-merge
    types:
      - closed
    paths:
      - plugin.yaml

jobs:
  DockerTag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Login to docker.io registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.ARGON_DOCKERHUB_USER }}
        password: ${{ secrets.ARGON_DOCKERHUB_TOKEN }}
    - name: Extract version
      run: "echo \"new_version=$(grep 'version: ' plugin.yaml | cut -d '\"' -f2)\" >> $GITHUB_ENV"
    - name: Change image versions to latest
      run: |
        docker pull aquasec/aqua-scanner:${{ env.new_version }}-amd64
        docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64 aquasec/aqua-scanner:latest-amd64
        docker push aquasec/aqua-scanner:latest-amd64
        
        docker pull aquasec/aqua-scanner:${{ env.new_version }}-arm64
        docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64 aquasec/aqua-scanner:latest-arm64
        docker push aquasec/aqua-scanner:latest-arm64
        
        docker manifest create aquasec/aqua-scanner:latest aquasec/aqua-scanner:latest-amd64 aquasec/aqua-scanner:latest-arm64
        docker manifest push aquasec/aqua-scanner:latest
