name: update docker images
on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - plugin.yaml
      - README-dockerhub.md

jobs:
  update-latest-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Login to docker.io registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ARGON_DOCKERHUB_USER }}
          password: ${{ secrets.ARGON_DOCKERHUB_TOKEN }}
      - name: login to Aqua Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}
          username: ${{ secrets.AQUASEC_ACR_USERNAME }}
          password: ${{ secrets.AQUASEC_ACR_PASSWORD }}
      - name: Extract version
        run: 'echo "new_version=$(grep ''version: '' plugin.yaml | cut -d ''"'' -f2)" >> $GITHUB_ENV'
      - name: Change image versions to latest
        run: |
          # amd
          docker pull aquasec/aqua-scanner:${{ env.new_version }}-amd64
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64 aquasec/aqua-scanner:latest-amd64
          docker push aquasec/aqua-scanner:latest-amd64
          # Handle transfer to aqua reg
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64 ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-amd64
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-amd64
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64 ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-amd64
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-amd64

          # arm
          docker pull aquasec/aqua-scanner:${{ env.new_version }}-arm64
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-arm64 aquasec/aqua-scanner:latest-arm64
          docker push aquasec/aqua-scanner:latest-arm64
          # Handle transfer to aqua reg
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-arm64 ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-arm64
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-arm64
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-arm64 ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-arm64
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-arm64

          # amd limited
          docker pull aquasec/aqua-scanner:${{ env.new_version }}-amd64-limited
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64-limited aquasec/aqua-scanner:latest-amd64-limited
          docker push aquasec/aqua-scanner:latest-amd64-limited
          # Handle transfer to aqua reg
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-amd64-limited
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-amd64-limited
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-amd64-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-amd64-limited
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-amd64-limited

          # arm limited
          docker pull aquasec/aqua-scanner:${{ env.new_version }}-arm64-limited
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-arm64-limited aquasec/aqua-scanner:latest-arm64-limited
          docker push aquasec/aqua-scanner:latest-arm64-limited
          # Handle transfer to aqua reg
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-arm64-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-arm64-limited
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-arm64-limited
          docker tag aquasec/aqua-scanner:${{ env.new_version }}-arm64-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-arm64-limited
          docker push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-arm64-limited
  
          # Multiarch For Version (Aqua reg)
          docker manifest create ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }} ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-amd64 ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-arm64
          docker manifest push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}

          # Multiarch For Version Limited (Aqua reg)
          docker manifest create ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-amd64-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-arm64-limited
          docker manifest push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:${{ env.new_version }}-limited

          # Multiarch Latest
          docker manifest create aquasec/aqua-scanner:latest aquasec/aqua-scanner:latest-amd64 aquasec/aqua-scanner:latest-arm64
          docker manifest push aquasec/aqua-scanner:latest
          # Handle transfer to aqua reg
          docker manifest create ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-amd64 ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-arm64
          docker manifest push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest

          # Multiarch Latest Limited
          docker manifest create aquasec/aqua-scanner:latest-limited aquasec/aqua-scanner:latest-amd64-limited aquasec/aqua-scanner:latest-arm64-limited
          docker manifest push aquasec/aqua-scanner:latest-limited
          # Handle transfer to aqua reg
          docker manifest create ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-amd64-limited ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-arm64-limited
          docker manifest push ${{ secrets.AQUASEC_ACR_REGISTRY_NAME }}/aqua-scanner:latest-limited
      - name: DockerHub description update
        uses: peter-evans/dockerhub-description@dc67fad7001ef9e8e3c124cb7a64e16d0a63d864 # 3.4.2
        with:
          username: ${{ secrets.ARGON_DOCKERHUB_USER }}
          password: ${{ secrets.ARGON_DOCKERHUB_TOKEN }}
          repository: aquasec/aqua-scanner
          readme-filepath: ./README-dockerhub.md
      - name: Update tag to latest
        uses: richardsimko/update-tag@e173a8ef8f54ab526a91dad6139a25efed62424c # v1.0.11
        with:
          tag_name: ${{ env.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TAG_GH_TOKEN }}
