on:
  pull_request:
    branches: 
      - tag-docker-on-merge
    types:
      - closed
    paths:
      - plugin.yaml

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR was merged: ${{github.event.pull_request}}
