name: testing for PR

on:
  pull_request:

jobs:
  validate-secrets-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint -d relaxed pkg/scanner/trivy-secret.yaml

  build:
    name: testing PR build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "link": ""https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}""
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CODE_TEAM_SLACK_WEBHOOK }}
