name: trivy-plugin-aqua release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: releasing trivy-plugin-aqua
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.18'
      - run: go version

      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update plugin Links
        run: |
          sed  -e "s/PLACEHOLDERVERSION/${{github.ref_name}}/g" .github/plugin_template.yaml > plugin.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "update-plugin-links-${{github.ref_name}}"
          title: "Update Plugin Artifacts Links for ${{github.ref_name}}"
          delete-branch: true
          base: master
          add-paths: |
            plugin.yaml
