name: tag update

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "new_version"
        type: string
        required: true
  
jobs:
  build:
    name: Build
    runs-on: arc-runner-set
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate aqua-pr-bot App token
        id: pr_bot_token
        uses: aquasecurity/.github-private/.github/actions/github-app-auth@github-app-migration
        with:
          app-id: ${{ secrets.AQUA_PR_BOT_APP_ID }}
          private-key: ${{ secrets.AQUA_PR_BOT_PRIVATE_KEY }}
          owner: aquasecurity
          repositories: trivy-plugin-aqua

      - name: Update tag to latest
        uses: richardsimko/update-tag@e173a8ef8f54ab526a91dad6139a25efed62424c # v1.0.11
        with:
          tag_name: ${{ inputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ steps.pr_bot_token.outputs.token }}
